### PR TITLE
Refactor to use riot.js framework

### PR DESCRIPTION
**Pull request by krasch**
possible issues: seems like sometimes the queue is not updated correctly (possibly only when adding new tracks). not successful in triggering this error yet

### CODE REVIEW

**Comment by petterarvidsson** [comment]
@krasch Super neat! :+1: 
Regarding the web socket delay. Maybe we could have a top level riot tag that loads all tags and opens the socket? Then it can be done after tags are loaded which would solve the problem.

**Comment by petterarvidsson** [comment]
One comment would be the lack of newlines at the end of the files.

**Comment by krasch** [comment]
top-level riot tag done. seems to help with the timing issues!
also added newlines

**Comment by petterarvidsson** [comment]
@krasch Nice! I'd say let's merge this one!

**Pull request merged**
